#!/bin/bash

src_venv=${1%/}
new_venv=${2%/}

src_venv_dir=$WORKON_HOME/$src_venv
new_venv_dir=$WORKON_HOME/$new_venv

pyver=$(ls -1 $new_venv_dir/lib | grep python | sed -e 's/python//')

src_hashbang="#!$src_venv_dir/"
new_hashbang="#!$new_venv_dir/"
src_venv_name=`basename $src_venv_dir`
libdir="lib/python$pyver/site-packages"

pthfile=$new_venv_dir/$libdir/$src_venv_name.pth
echo "Adding $pthfile to $new_venv"
echo "$src_venv_dir/$libdir" > $pthfile

for i in $src_venv_dir/bin/*
do
    dest="$new_venv_dir/bin/$(basename $i)"
    if [ ! -e "$dest" ]
    then
        echo "Copying bin $i to $new_venv"
        hashbang=`head -c 2 $i`
        if [ "$hashbang" = "#!" ]
        then
            cp $i $dest
            sed -i '' -e "1s;^$src_hashbang;$new_hashbang;" $dest
            if grep -q 'EASY-INSTALL-ENTRY-SCRIPT' $dest
            then
                sed -i '' -e '/__name__/!s/==[0-9.]*//g' $dest
            fi
       else
            ln -s $i $new_venv_dir/bin
        fi
    fi
done

